server:
  port: 8980
spring:
  profiles:
    active: native
  application:
    name: config-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2